---
title: "Evaluation of weighted synthetic file"
output:
  html_document:
    df_print: paged
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: FALSE
      smooth_scroll: true
---


```{r runall, eval=FALSE, echo=FALSE}
# UPDATE THESE DIRECTORIES WHEN RUN ON A DIFFERENT SYSTEM ----
# ALSO UPDATE DIRECTORIES IN THE system_specific CHUNK BELOW ----
# use this to create a dated output file - just run the lines below manually

# the directory names must be hard-coded here - can't use getwd()

indir <- "D:/Dropbox/RPrograms PC/OSPC/EvaluateWtdSynFile/" # directory for this file
# outdir <- "D:/Google Drive/OSPC/synpuf_analyses/" # PUBLIC directory
outdir <- "D:/tcdir/"
rmdfn <- paste0(indir, "_main.rmd")  # input rmarkdown code (this file)
# outfn <- paste0(outdir, "eval_excl_taxcalc_", format(Sys.time(), "%Y-%m-%d"), ".html")

outfn <- paste0(outdir, "eval_", format(Sys.time(), "%Y-%m-%d-%H_%M"), ".html")
rmarkdown::render(rmdfn, output_format="html_document", output_file=outfn)

```


```{r mainSet options, echo=FALSE, cache=FALSE}
options(width=120)
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, fig.width=14, fig.height=10)
# Note: when saving maps (ggsave), width=16, height=9 seems to get rid of white space

```


```{r setup, echo=FALSE, warning=FALSE, message=FALSE, eval=TRUE}
## NOTE

source("./includes/libraries.r")
# note that when using dplyr's select function, I always identify it as dplyr::select because
# if synthpop is loaded plain select will not work as synthpop masks dplyr's select

source("./includes/functions.r")
source("./includes/globals_system_specific_boyd.r") # use a different version of this file if changing systems
source("./includes/globals_other.r")


# unfortunately I don't know a better way than the following to ensure that output in child docs goes to the right directory:
# gdir <- "D:/Dropbox/RPrograms PC/ProjectsCurrent/FedBudgetAndStates/results/graphics/"
#```{r childBEASLG, child="childBEASLG_NTA.rmd", eval=TRUE}
#```

```


```{r ONETIME_get_full_puf, include=FALSE, eval=FALSE}
# after creating and saving the puf as an rds file on local machine, set eval=FALSE so it is not rerun
puf.fn <- "puf2011.csv"

puf <- read_csv(paste0(pufdir, puf.fn), 
                col_types = cols(.default= col_double()), 
                n_max=-1)
saveRDS(puf, paste0(tc.dir, "puf.rds"))

```


```{r create_important_variables, include=FALSE}
puf.vnames <- get_puf_vnames()

source("./includes/define_synfile_names.r") # creates synfile.fnames and bad.MARS.files. Updated when new synthetic files created

#.. define the subset of files we will examine in this run ----
use.files <- c("synpuf8", "synthpop3")

files.order <- c("puf.full", use.files) # define the order of files in the output

```


```{r get_files, include=FALSE}
remove.vars <- c("penratio", "divratio", "E00100", "E09600") # temporary fix - variables to remove from boyd files

synfiles <- get_synfiles(use.files, synfile.fnames, remove.vars, bad.MARS.files)
synvars <- puf.vnames %>% filter(vname %in% str_to_lower(names(synfiles)))

puf.base <- get_puf.base(names(synfiles))

# stack the puf and synthetic files
stack <- bind_rows(puf.base, synfiles) %>%
  setNames(change_case(names(.))) %>%
  mutate(wt=s006 / 100,
         ftype=factor(ftype, levels=files.order))

stackvars <- tibble(variable=names(stack), byvar=str_to_lower(variable)) %>%
  left_join(puf.vnames %>% select(byvar=vname, vdesc)) %>%
  select(-byvar) %>%
  arrange(variable)

# glimpse(stack)
# Now we can finally start our analysis

```


# Initial simple checks
```{r child_simple_checks, child="./child_rmd_files/simple_checks.rmd", eval=TRUE}
```


# Cumulative distributions of weighted variables
```{r child_CDFanalysis, child="./child_rmd_files/CDFanalysis.rmd", eval=TRUE}
```



