---
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r taxinfo, include=FALSE, eval=FALSE}
# Info on preparing a files for Tax-Calculator
# https://pslmodels.github.io/Tax-Calculator/

# The only required input variables are RECID (a unique filing-unit record identifier) and
# MARS (a positive-valued filing-status indicator). 

# Other variables in the input file must have variable names that are listed in the Input Variables
# section for them to affect the tax calculations. 

# Any variable listed in Input Variables that is not in an input file is automatically set to zero
# for every filing unit. 

# Variables in the input file that are not listed in Input Variables are ignored by Tax-Calculator.

# Tax-Calculator expects that the filing-unit total for each of several earnings-related variables
# is split between the taxpayer and the spouse....do this earnings splitting.

# e00200 = e00200p + e00200s  # wages
# e00900 = e00900p + e00900s  # business income or loss
# e02100 = e02100p + e02100s  # Schedule F net profit/loss

# You will get an error message from Tax-Calculator, and it will stop running, if you do not split the filing-unit
# amount between taxpayer and spouse so that the above equations hold for each filing unit in the input file.

# ...Tax-Calculator expects that the 
# value of ordinary dividends (e00600) will be no less than the value of qualified dividends (e00650) for each
# filing unit.

# And it also expects that the value of total pension and annuity income (e01500) will be no less than
# the value of taxable pension and annuity income (e01700) for each filing unit.

```


```{r prep_file_for_taxcalc, include=FALSE, eval=TRUE}
# Prepare a version of the stacked file that is ready to be run through Tax-Calculator

# files we want to run through tc - will change as new synpuf's are created, defined in use.files
tc.files <- c("puf.full", use.files)
# names(stack)

# exclude any vars that have NAs; early on I had some but I think they are all good now
# excl.vars <- c("DSI", "f6251", "MIDR", "fded", "EIC", "n24", "f2441", "e09800", "e09700", "p08000")
excl.vars <- NULL
tc.vars <- setdiff(names(stack), excl.vars)

tc.base <- stack %>%
  filter(ftype %in% tc.files) %>%
  select(tc.vars) %>%
  mutate(RECID=row_number()) %>%
  do(impose_variable_rules(.)) %>% # not needed for synpuf5 and later
  do(prime_spouse_splits(.))

# write tcbase to a file, because the Tax-Calculator CLI reads a csv file
tc.fn <- "tcbase.csv"
write_csv(tc.base, paste0(tc.dir, tc.fn))

# summary(tc.base)

```


```{r run_tc, include=FALSE, eval=TRUE}
# run Tax-Calculator. It will write (dump) its results to a csv file in the output director tc.dir

# The output filename will be of the form:
#   fname-
#   2-digit-tax-year
#   -#-#-#.csv  (this may change depending on parameters used on the CLI call, I don't know)
# Thus, if the input file is tcbase.csv and the taxyear is 2013, the output filename will be:
#   tcbase-13-#-#-#.csv

cmd <- tc.wincmd(tc.fn, tc.dir, tc.cli)
# cmd    # a good idea to look at the command

a <- proc.time()
system(cmd) # CAUTION: this will overwrite any existing output file that had same input filename!
proc.time() - a # it can easily take 5-10 minutes depending on the size of the input file

```


```{r get_tcresults, include=FALSE, eval=TRUE}

# Construct the name of the output file. CAUTION: the taxyear, currently 2013, might be different in future runs
# "tcbase-13-#-#-#.csv"
tc.outfn <- paste0(str_remove(basename(tc.fn), ".csv"), "-", 13, "-#-#-#", ".csv")
tc.output <- read_csv(paste0(tc.dir, tc.outfn), 
                      col_types = cols(.default= col_double()), 
                      n_max=-1)
# names(tc.output) %>% sort

# create analysis file by merging our base file with any variables we want from Tax-Calculator
afile <- tc.base %>%
  left_join(tc.output %>% select(RECID, c00100, taxbc))

# names(afile) %>% sort
# 
# afile %>%
#   group_by(ftype) %>%
#   summarise_at(vars(c00100, e00200, e00200p, e00650, e00600, taxbc), funs(sum(. * wt) / 1e9))

```



## Graph cumulative distribution of variables vs. AGI
### Wages
```{r echo=FALSE, eval=TRUE}
tmp <- afile %>%
  select(ftype, wt, e00200, c00100) %>%
  group_by(ftype) %>%
  arrange(c00100) %>%
  mutate(cum.pct=cumsum(wt * e00200) / sum(wt * e00200))

capt <- "- x-axis (AGI) is log10 scale\n- For display purposes x-axis is truncated at left to only show AGI >= $10,000"
gtitle <- "Cumulative distribution of weighted wages (e00200) vs. Adjusted gross income"
gsub <- "Aggregate records excluded"
ylab <- "Cumulative proportion of the sum of weighted wages (e00200)"

sq10 <- c(0, 10e3, 25e3, 50e3, 100e3, 250e3, 500e3, 750e3, 1e6, 1.5e6, 2e6, 3e6, 4e6, 5e6, 10e6, 25e6, 50e6, 100e6)
xlabs <- scales::comma(sq10 / 1e3)
xscale.l10 <- scale_x_log10(name="AGI in $ thousands", breaks=sq10, labels=xlabs)

tmp %>%
  filter(c00100 > 10e3) %>%
  ggplot(aes(c00100, cum.pct, colour=ftype)) + 
  geom_line(size=1.5) +
  theme_bw() +
  ggtitle(gtitle, subtitle=gsub) +
  labs(caption=capt) +
  scale_y_continuous(name=ylab, breaks=c(seq(0, .9, .05), seq(.92, 1, .02))) +
  xscale.l10 +
  theme(axis.text.x=element_text(angle=45, size=10, hjust=1, colour="black")) +
  theme(plot.caption = element_text(hjust=0, size=rel(.8)))

```


### Tax before credit
```{r echo=FALSE, eval=TRUE}
tmp <- afile %>%
  select(ftype, wt, taxbc, c00100) %>%
  group_by(ftype) %>%
  arrange(c00100) %>%
  mutate(cum.pct=cumsum(wt * taxbc) / sum(wt * taxbc))

capt <- "- x-axis (AGI) is log10 scale\n- For display purposes x-axis is truncated at left to only show AGI >= $10,000"
gtitle <- "Cumulative distribution of weighted tax before credit (taxbc) vs. Adjusted gross income"
gsub <- "Aggregate records excluded"
ylab <- "Cumulative proportion of the sum of weighted tax before credit (taxbc)"

sq10 <- c(0, 10e3, 25e3, 50e3, 100e3, 250e3, 500e3, 750e3, 1e6, 1.5e6, 2e6, 3e6, 4e6, 5e6, 10e6, 25e6, 50e6, 100e6)
xlabs <- scales::comma(sq10 / 1e3)
xscale.l10 <- scale_x_log10(name="AGI in $ thousands", breaks=sq10, labels=xlabs)

tmp %>%
  filter(c00100 > 10e3) %>%
  ggplot(aes(c00100, cum.pct, colour=ftype)) + 
  geom_line(size=1.5) +
  theme_bw() +
  ggtitle(gtitle, subtitle=gsub) +
  labs(caption=capt) +
  scale_y_continuous(name=ylab, breaks=c(seq(0, .9, .05), seq(.92, 1, .02))) +
  xscale.l10 +
  theme(axis.text.x=element_text(angle=45, size=10, hjust=1, colour="black")) +
  theme(plot.caption = element_text(hjust=0, size=rel(.8)))
```


## Examine results by AGI range
```{r agirange_data, include=FALSE, eval=TRUE}
agiranges <- c(-Inf, 0, 25e3, 50e3, 75e3, 100e3, 200e3, 500e3, 1e6, 10e6, Inf)
glimpse(afile)

analysis.vars <- c(setdiff(continuous.vars, "wt"), "c00100", "taxbc")

# wsb <- function(var, wt){sum(var * wt) / 1e9} # weighted sum in $ billions

wtd.totals1 <- afile %>%
  select(ftype, wt, analysis.vars) %>%
  mutate(agirange=cut(c00100, agiranges, right=FALSE)) %>%
  gather(variable, value, -ftype, -agirange, -wt) %>%
  group_by(ftype, agirange, variable) %>%
  summarise(value=sum(value * wt) / 1e9)
glimpse(wtd.totals1)

wtd.totals2 <- afile %>%
  select(ftype, wt, analysis.vars) %>%
  mutate(agirange=cut(c00100, agiranges, right=FALSE)) %>%
  group_by(ftype, agirange) %>%
  summarise(n=n(), wt=sum(wt)) %>%
  gather(variable, value, -ftype, -agirange)
glimpse(wtd.totals2)

wtd.totals <- bind_rows(wtd.totals1, wtd.totals2)

f <- function(var){
  df <- wtd.totals %>%
    filter(variable==var) %>%
    spread(ftype, value) %>%
    adorn_totals(where="row") %>%
    mutate_at(vars(-c(1:3)), 
              funs(diff=. - puf.full,
                   pdiff=(. - puf.full) / puf.full * 100)) %>%
    left_join(synvars %>% select(variable=vname, vdesc)) %>%
    kable(caption="Weighted sums by AGI range, in $ billions, plus differences and pct differences",
          digits=c(0, 0, rep(1, length(use.files) + 1), rep(1, length(use.files)), rep(1, length(use.files)), 0), 
          format.args=list(big.mark = ','))
  return(df)
}


```

```{r agirange_summaries, echo=FALSE, tidy=FALSE, eval=TRUE, results='asis'}
# 
# oddly, results='asis' is needed when printing kable inside a for loop
# see https://github.com/yihui/knitr/issues/886
# f(analysis.vars[1])
# f(analysis.vars[2])
library("kableExtra")
for(var in c("n", "wt", analysis.vars)) print(f(var) %>% kable_styling() %>% scroll_box(width = "1200px"))

```



